// GENERATED FILE — do not hand-edit.
// Produced by apps/desktop/scripts/abnf-to-lezer.mjs from specs/todotxt.abnf.
// Regenerate: node apps/desktop/scripts/abnf-to-lezer.mjs

// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {todotxtTokens, todotxtContext} from "./todotxt.tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "zQYQROOOtQPO'#ChOOQP'#Cm'#CmOOQP'#Cj'#CjQYQROOOOQP,59S,59SOOQP-E6h-E6h",
  stateData: "!R~OVOSWOS~OPQOQQORQOSPOUQOYQOZQO]QO~ORTOTTO~OYZ]Z~",
  goto: "qbPPPPPPPPPPPPcPgPPmTQOSQSORUSTROS",
  nodeNames: "⚠ CompletionMarker Priority Date TagKey TagValue IdTag Space Newline File Project Context Tag Text",
  maxTerm: 17,
  context: todotxtContext,
  skippedNodes: [0,7,8],
  repeatNodeCount: 1,
  tokenData: "#z~RWq{k{|!S|!bk!b!c#O!c#sk#t;'Sk;'S;=`|<%lOk~pS]~q#sk#t;'Sk;'S;=`|<%lOk~!PP;=`<%lk~!XS]~q#s!e#t;'S!e;'S;=`!x<%lO!e~!lSY~]~q#s!e#t;'S!e;'S;=`!x<%lO!e~!{P;=`<%l!e~#TS]~q#s#a#t;'S#a;'S;=`#t<%lO#a~#hSZ~]~q#s#a#t;'S#a;'S;=`#t<%lO#a~#wP;=`<%l#a",
  tokenizers: [todotxtTokens, 0],
  topRules: {"File":[0,9]},
  tokenPrec: 44
})
