// GENERATED FILE — do not hand-edit.
// Produced by apps/desktop/scripts/abnf-to-lezer.mjs from specs/todotxt.abnf.
// Regenerate: node apps/desktop/scripts/abnf-to-lezer.mjs

// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  CompletionMarker = 1,
  Priority = 2,
  Date = 3,
  TagKey = 4,
  TagValue = 5,
  IdTag = 6,
  Space = 7,
  Newline = 8,
  File = 9,
  Project = 10,
  Context = 11,
  Tag = 12,
  Text = 13
