#!/usr/bin/env bash
# Regenerates apps/desktop/src/lib/wasm-core/ from crates/txtodo-ffi (design §2.3, plan M7:
# desktop-edit-popover, desktop-conflict-review). The output is a generated artifact — committed,
# regenerated by this script, never hand-edited.
#
# Needs: rustup target add wasm32-unknown-unknown
#        cargo install wasm-bindgen-cli --version <matching crates/txtodo-ffi's wasm-bindgen dep>
# Ref: https://rustwasm.github.io/docs/wasm-bindgen/reference/cli.html
set -euo pipefail
cd "$(dirname "$0")/../../.."

cargo build -p txtodo-ffi --target wasm32-unknown-unknown --release

wasm-bindgen \
  target/wasm32-unknown-unknown/release/txtodo_ffi.wasm \
  --out-dir apps/desktop/src/lib/wasm-core \
  --out-name txtodo_ffi \
  --target web \
  --typescript
