[package]
name = "txtodo-core-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.txtodo-core]
path = ".."

[[bin]]
name = "parse_line"
path = "fuzz_targets/parse_line.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parse_file"
path = "fuzz_targets/parse_file.rs"
test = false
doc = false
bench = false

[[bin]]
name = "slug"
path = "fuzz_targets/slug.rs"
test = false
doc = false
bench = false

[[bin]]
name = "slug_windows_safe"
path = "fuzz_targets/slug_windows_safe.rs"
test = false
doc = false
bench = false
